import {initMap,setScene,focusRecord} from './map.js';
import {initScrolly} from './scrolly.js';
import {initExplainers} from './explainers.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const present=v=>v!==null&&v!==undefined&&v!==''; let features=[],sources=[];
const evidence={located:'● referência atual localizada',reconstructed:'╍ geometria em reconstrução',unlocated:'○ evento documental sem localização exata'};
function sourceBlock(ids=[]){if(!ids.length)return '';const items=ids.map(id=>sources.find(s=>s.id===id)).filter(Boolean);return `<details class="scene-sources"><summary>Fontes desta cena</summary>${items.map(s=>`<p><b>${esc(s.tipo)}</b> · ${esc(s.autor||'Autoria não informada')}<br>${esc(s.titulo||'Título não informado')}${s.folios?` · fólio(s) ${esc(s.folios)}`:''}${s.url?` · <a href="${esc(s.url)}">acessar</a>`:' · referência sem URL no acervo'}</p>`).join('')}</details>`}
function mediaSlot(m){return m?`<figure class="media-slot"><div aria-hidden="true">${esc(m.placeholder)}</div><figcaption><b>${esc(m.label)}</b>${m.meta?`<br>${esc(m.meta)}`:''}<br><span>${esc(m.status)}</span></figcaption></figure>`:''}
function explainer(){return `<div class="rights-explainer" data-explainer><div class="rights-stage" aria-live="polite"><p class="rights-owner">Senhorio direto <span>domínio direto</span></p><div class="parcel">TERRA</div><p class="rights-user">Foreiro ou enfiteuta <span>domínio útil</span></p></div><div class="explainer-nav"><button type="button" data-prev aria-label="Etapa anterior">←</button><span data-counter></span><button type="button" data-next>Avançar →</button></div><p data-explainer-text></p></div>`}
function transform(){return `<div class="transformation" aria-label="Transformação documental esquemática">${['Território','Aforamento','Loteamento','Lote 25','Edifício','Unidade','Matrícula'].map((x,i)=>`<div><span>${String(i+1).padStart(2,'0')}</span><b>${x}</b>${i<6?'<i>→</i>':''}</div>`).join('')}</div><p class="scheme-note">ESQUEMA CONCEITUAL — NÃO GEOGRÁFICO. A matrícula de uma unidade não representa o perímetro de todo o terreno.</p>`}
function microstory(scene){return `<article id="${scene.id}" class="scene microstory"><header><p class="scene-no">Cena ${scene.number} · ${esc(scene.eyebrow)}</p><h2>${esc(scene.title)}</h2><p>${esc(scene.body)}</p></header>${mediaSlot(scene.media)}${scene.milestone?`<p class="milestone">${esc(scene.milestone)}</p>`:''}<div class="certainty"><div><h3>O que os documentos permitem afirmar</h3><p>${esc(scene.known)}</p></div><div><h3>O que ainda estamos investigando</h3><p>${esc(scene.unknown)}</p></div></div>${sourceBlock(scene.sourceIds)}</article>`}
function renderScene(s){if(s.mode==='MICROSTORY')return microstory(s);if(s.mode==='EXPLAINER')return `<article id="${s.id}" class="scene explainer"><p class="scene-no">Cena ${s.number} · ${esc(s.eyebrow)}</p><h2>${esc(s.title)}</h2>${explainer()}${sourceBlock(s.sourceIds)}</article>`;if(s.mode==='TRANSFORM')return `<article id="${s.id}" class="scene transform"><p class="scene-no">Cena ${s.number} · ${esc(s.eyebrow)}</p><h2>${esc(s.title)}</h2><p class="display-copy">${esc(s.body)}</p>${transform()}${sourceBlock(s.sourceIds)}</article>`;return `<article id="${s.id}" class="story-step" data-scene-id="${s.id}"><p class="scene-no">Cena ${s.number} · Ato ${s.act}</p><p class="kicker">${esc(s.eyebrow)}</p><h2>${esc(s.title)}</h2><p>${esc(s.body)}</p>${s.metric?`<div class="big-metric">${esc(s.metric)}</div>`:''}${s.evidenceType?`<p class="evidence-label">${evidence[s.evidenceType]}</p>`:''}${mediaSlot(s.media)}${s.note?`<p class="scene-note">${esc(s.note)}</p>`:''}${sourceBlock(s.sourceIds)}</article>`}
function renderNarrative(scenes){const out=[];let mapOpen=false,mapIndex=-1;for(const s of scenes){if(s.mode==='MAP'){if(!mapOpen){mapIndex++;out.push(`<section class="map-chapter"><div class="story-map"><div class="map" id="map-${mapIndex}"></div><p class="map-caption">Mapa contemporâneo</p><div class="map-key">● apenas referências localizadas</div></div><div class="story-steps">`);mapOpen=true}s.mapIndex=mapIndex;out.push(renderScene(s))}else{if(mapOpen){out.push('</div></section>');mapOpen=false}out.push(renderScene(s))}}if(mapOpen)out.push('</div></section>');document.querySelector('#narrative').innerHTML=out.join('')}
function showRecord(id){const f=features.find(x=>x.properties.id===id);if(!f)return;const r=f.properties,fields=[['Instituição',r.instituicao],['Relação fundiária',r.relacao_fundiaria],['Período / data',[r.data_inicio,r.data_fim].filter(Boolean).join('–')],['Endereço / topônimo',r.endereco_atual||r.toponimo_historico],['Matrícula',r.matricula_atual],['Área',r.area],['Dimensões',r.dimensoes],['Fonte',[r.fonte_primaria,r.folio].filter(Boolean).join(', ')],['Status documental',r.status_documental],['Precisão geográfica',r.grau_correspondencia_geografica],['Observações / limitações',r.observacoes]];document.querySelector('#record-panel').innerHTML=`<button class="panel-close" type="button">Fechar</button><p class="panel-kicker">${f.geometry?'● REFERÊNCIA ATUAL LOCALIZADA':'○ SEM GEOMETRIA PUBLICADA'}</p><h3>${esc(r.titulo)}</h3><dl>${fields.filter(([,v])=>present(v)).map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl>`;document.querySelector('.panel-close').onclick=()=>document.querySelector('#record-panel').innerHTML='<p class="panel-placeholder">Selecione um registro para consultar sua ficha.</p>';focusRecord(f)}
function renderRecords(filter='todos'){const list=features.filter(f=>filter==='todos'||f.properties.tipo_registro===filter);document.querySelector('#result-count').textContent=`${list.length} registros`;document.querySelector('#record-list').innerHTML=list.map(f=>`<button class="record-button" data-id="${esc(f.properties.id)}"><span><strong>${esc(f.properties.titulo)}</strong><small>${esc(f.properties.instituicao)}</small></span><span>${esc(f.properties.endereco_atual||f.properties.toponimo_historico||'Localização não determinada')}</span><em>${f.geometry?'● MAPA':'○ FICHA'} →</em></button>`).join('');document.querySelectorAll('.record-button').forEach(b=>b.onclick=()=>showRecord(b.dataset.id))}
async function start(){const [g,c,f]=await Promise.all(['registros.geojson','cenas.json','fontes.json'].map(x=>fetch(`./data/${x}`).then(r=>{if(!r.ok)throw Error(`${x}: ${r.status}`);return r.json()})));features=g.features;sources=f;renderNarrative(c);initMap(g,showRecord);initScrolly(c,setScene);initExplainers();renderRecords();document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});renderRecords(b.dataset.filter)});document.querySelector('#source-index').innerHTML=sources.map(s=>`<div><b>${esc(s.autor||s.tipo)}</b><span>${esc(s.titulo||s.tipo)} · ${s.url?'link disponível':'referência bibliográfica/arquivística sem URL'}</span></div>`).join('')}
start().catch(e=>document.querySelector('#narrative').innerHTML=`<p class="load-error">Não foi possível carregar a reportagem: ${esc(e.message)}</p>`);
